### ISSUE TITLE
JAVA 21 - GWT 2.12.0 - Unable to get known Configuration java.util.ServiceConfigurationError

### ISSUE THREAD

**Issue by ibrahimali123** [gwtproject/gwt-site#374]
My Project is running locally correctly, but it gives me this error in the Google app engine logs staging and is not working. I don't know what this error means.

`Unable to get known Configuration java.util.ServiceConfigurationError: at     org.eclipse.jetty.util.ServiceLoaderSpliterator$ServiceProvider.get(ServiceLoaderSpliterator.java:101)
    at org.eclipse.jetty.ee8.webapp.Configurations.lambda$getKnown$0(Configurations.java:77)
        at org.eclipse.jetty.util.ServiceLoaderSpliterator.tryAdvance(ServiceLoaderSpliterator.java:46)
    at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
    at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
    at org.eclipse.jetty.ee8.webapp.Configurations.getKnown(Configurations.java:75)
    at org.eclipse.jetty.ee8.webapp.WebAppContext.preConfigure(WebAppContext.java:447)
    at org.eclipse.jetty.ee8.webapp.WebAppContext.doStart(WebAppContext.java:500)
    at com.google.apphosting.runtime.jetty.ee8.AppEngineWebAppContext.doStart(AppEngineWebAppContext.java:237)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
    at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:491)
    at org.eclipse.jetty.server.handler.ContextHandler.lambda$doStart$0(ContextHandler.java:754)
    at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1452)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:754)
    at org.eclipse.jetty.ee8.nested.ContextHandler$CoreContextHandler.doStart(ContextHandler.java:2269)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.addManaged(ContainerLifeCycle.java:482)
    at org.eclipse.jetty.server.handler.HotSwapHandler.setHandler(HotSwapHandler.java:74)
    at com.google.apphosting.runtime.jetty.AppVersionHandler.ensureHandler(AppVersionHandler.java:97)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:235)
    at com.google.apphosting.runtime.RequestRunner.dispatchServletRequest(RequestRunner.java:349)
    at com.google.apphosting.runtime.RequestRunner.dispatchRequest(RequestRunner.java:234)
    at com.google.apphosting.runtime.RequestRunner.run(RequestRunner.java:200)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:273)
    at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.ServiceConfigurationError: org.eclipse.jetty.ee8.webapp.Configuration: org.eclipse.jetty.ee8.webapp.WebAppConfiguration not a subtype
    at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
    at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
    at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
    at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
    at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
    at org.eclipse.jetty.util.ServiceLoaderSpliterator.tryAdvance(ServiceLoaderSpliterator.java:37)
    ... 25 more
`

I am using gwt-dev 2.12.0 (the latest one) and using jetty-ee8

Here is my appengine-web.xml:
`
<property name="appengine.use.EE8" value="true"/>
`

This is a sample from the dependency tree:
`
+- org.gwtproject:gwt-dev:jar:2.11.0:compile
|  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
|  +- com.google.code.gson:gson:jar:2.6.2:compile
|  +- org.ow2.asm:asm:jar:9.2:compile
|  +- org.ow2.asm:asm-util:jar:9.2:compile
|  |  +- org.ow2.asm:asm-tree:jar:9.2:compile
|  |  \- org.ow2.asm:asm-analysis:jar:9.2:compile
|  +- org.ow2.asm:asm-commons:jar:9.2:compile
[INFO] |  +- colt:colt:jar:1.2.0:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  +- com.ibm.icu:icu4j:jar:63.1:compile
[INFO] |  +- tapestry:tapestry:jar:4.0.2:compile
[INFO] |  +- org.eclipse.jetty:jetty-webapp:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-xml:jar:9.4.44.v20210927:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-servlet:jar:9.4.44.v20210927:compile
[INFO] |  |     +- org.eclipse.jetty:jetty-security:jar:9.4.44.v20210927:compile
[INFO] |  |     |  \- org.eclipse.jetty:jetty-server:jar:9.4.44.v20210927:compile
[INFO] |  |     \- org.eclipse.jetty:jetty-util-ajax:jar:9.4.44.v20210927:compile
[INFO] |  +- org.eclipse.jetty:jetty-servlets:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-continuation:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-util:jar:9.4.44.v20210927:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-io:jar:9.4.44.v20210927:compile
[INFO] |  +- org.eclipse.jetty:jetty-annotations:jar:9.4.44.v20210927:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-plus:jar:9.4.44.v20210927:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-jndi:jar:9.4.44.v20210927:compile
[INFO] |  |  \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  \- org.eclipse.jetty:apache-jsp:jar:9.4.44.v20210927:compile
[INFO] |     +- org.eclipse.jetty.toolchain:jetty-schemas:jar:3.1.2:compile
[INFO] |     \- org.mortbay.jasper:apache-jsp:jar:8.5.70:compile
[INFO] |        +- org.mortbay.jasper:apache-el:jar:8.5.70:compile
[INFO] |        \- org.eclipse.jdt:ecj:jar:3.19.0:compile
`

Is this because gwt-dev using jetty jars 9.4.44.v20210927?

**Comment by niloc132** [comment]
I don't think there's enough info here to be 100% certain, but a few points of confusion:
 * This dependency tree shows GWT 2.11, but the issue title says 212? 
 * Is this a new change with GWT a GWT update? What else did you change when this error started? 
 * You should not have gwt-dev or its dependencies on your server classpath - then these dependencies won't be present when you run your server
 * I think `org.eclipse.jetty.ee8.webapp.Configuration` is a Jetty 12 type? Again, probably means that you are mixing the compiler into the server's classpath, instead of keeping it in the client project only.
 * This is the repo for the gwtproject.org website, the GWT project issue tracker is at github.com/gwtproject/gwt - but the mailing list is at https://groups.google.com/g/google-web-toolkit - that is probably the best place for a question like this

**Comment by niloc132** [comment]
Closing as stale, no response in over a month.
