### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by nweeger** [gwtproject/gwt-site#71]
When I do `mvn clean install -Pgrunt` I get the following errors:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building markdown 2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.3:clean (default-clean) @ gwt-site ---
[INFO] Deleting file set: /home/nicolas/Projets/GWT/gwt-site/target (included: [**], excluded: [])
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.20:install-node-and-npm (install node and npm) @ gwt-site ---
[INFO] Node v0.10.33 is already installed.
[INFO] Found NPM version 1.4.28
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.20:npm (npm install) @ gwt-site ---
[INFO] Running 'npm install --color=false' in /home/nicolas/Projets/GWT/gwt-site
[INFO] npm WARN package.json GWTSite@2.0.0 No repository field.
[INFO] 
[INFO] > optipng-bin@0.3.11 postinstall /home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/optipng-bin
[INFO] > node index.js
[INFO] 
[INFO] 
[INFO] > jpegtran-bin@0.2.8 postinstall /home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/jpegtran-bin
[INFO] > node index.js
[INFO] 
[INFO] 
[INFO] > pngquant-bin@0.1.7 postinstall /home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin
[INFO] > node index.js
[INFO] 
[INFO] ✓ pre-build test passed successfully
[INFO] 
[INFO] > gifsicle@0.1.7 postinstall /home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/gifsicle
[INFO] > node index.js
[INFO] 
[INFO] ⚠ pre-build test failed, compiling from source...
[INFO] 
[INFO] stream.js:94
[INFO]       throw er; // Unhandled stream error in pipe.
[INFO]             ^
[INFO] Error: invalid tar file
[INFO]     at Extract.Parse._startEntry (/home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:145:13)
[INFO]     at Extract.Parse._process (/home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:127:12)
[INFO]     at BlockStream.<anonymous> (/home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:47:8)
[INFO]     at BlockStream.emit (events.js:95:17)
[INFO]     at BlockStream._emitChunk (/home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/block-stream/block-stream.js:145:10)
[INFO]     at BlockStream.resume (/home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/block-stream/block-stream.js:58:15)
[INFO]     at Extract.Reader.resume (/home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream/lib/reader.js:255:34)
[INFO]     at DirWriter.<anonymous> (/home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/extract.js:57:8)
[INFO]     at DirWriter.emit (events.js:92:17)
[INFO]     at /home/nicolas/Projets/GWT/gwt-site/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream/lib/dir-writer.js:39:8
[INFO] 
[INFO] npm ERR! gifsicle@0.1.7 postinstall: `node index.js`
[INFO] npm ERR! Exit status 8
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the gifsicle@0.1.7 postinstall script.
[INFO] npm ERR! This is most likely a problem with the gifsicle package,
[INFO] npm ERR! not with npm itself.
[INFO] npm ERR! Tell the author that this fails on your system:
[INFO] npm ERR!     node index.js
[INFO] npm ERR! You can get their info via:
[INFO] npm ERR!     npm owner ls gifsicle
[INFO] npm ERR! There is likely additional logging output above.
[INFO] npm ERR! System Linux 3.2.0-4-amd64
[INFO] npm ERR! command "/home/nicolas/Projets/GWT/gwt-site/node/node" "/home/nicolas/Projets/GWT/gwt-site/node/npm/bin/npm-cli.js" "install" "--color=false"
[INFO] npm ERR! cwd /home/nicolas/Projets/GWT/gwt-site
[INFO] npm ERR! node -v v0.10.33
[INFO] npm ERR! npm -v 1.4.28
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! not ok code 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.142s
[INFO] Finished at: Wed Apr 01 22:30:09 CEST 2015
[INFO] Final Memory: 11M/218M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.20:npm (npm install) on project gwt-site: Failed to run task: 'npm install --color=false' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by tskardal** [comment]
I'm also unable to compile, but I get a different error.

> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm (install node and npm) on project gwt-site: Execution install node and npm of goal com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm: org/slf4j/helpers/MarkerIgnoringBase

**Comment by florian-f** [comment]
what happens when you try it this way:

* `npm install`
* `grunt`
* `mvn clean install`

**Comment by feedm3** [comment]
I had the same error but using the commands from @florian-f  worked :+1:
